version: '3.8'
services:
  account_service:
    build:
      context: ./account_service
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/account_service:/app/database:rw
    networks:
      - backend_network

  analytics_service:
    build:
      context: ./analytics_service
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/analytics_service:/app:rw
    networks:
      - backend_network

networks:
  backend_network: