version: '3.8'
services:
  account_service:
    build:
      context: ./account_service
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/account_service
    networks:
      - backend_network

  analytics_service:
    build:
      context: ./analytics_service
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/analytics_service
    networks:
      - backend_network